import "@/public/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/components/navbar/Header";
import Providers from "@/components/progressBarProvider";
import { RootProvider } from 'fumadocs-ui/provider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Blocks",
  description: "Generated by create next app",
};

export default function BlockLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" suppressHydrationWarning >
      <body className={inter.className} style={{
        // display: 'flex',
        // flexDirection: 'column',
        // minHeight: '100vh',
      }
      } >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <RootProvider>
            <Header />
            <Providers>
              {children}
            </Providers>
          </RootProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

